version: '3.4'

services:
  php:
    environment:
      APP_ENV: test
    volumes:
      - ${DIRECTORY}/api:/srv/api:rw,cached

  api:
    volumes:
      - ${DIRECTORY}/api/public:/srv/api/public:ro

  mock_discovery:
    image: rodolpheche/wiremock:2.19.0-alpine
    volumes:
      - ${DIRECTORY}/mock/discovery/stubs:/home/wiremock:rw
    networks:
      default:
        aliases:
          - forms_mock_discovery

  mock_formio:
    image: rodolpheche/wiremock:2.19.0-alpine
    volumes:
      - ${DIRECTORY}/mock/formio/stubs:/home/wiremock:rw
    networks:
      default:
        aliases:
          - forms_mock_formio
