services:
  app.event_listener.form.type.formio:
    class: AppBundle\EventListener\Form\Type\FormioListener
    arguments:
      - '@service_container'
    tags:
      - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\Form, event: postPersist }
